**Universidad Nacional de Colombia**

**Diplomado en Inteligencia Artificial y Aprendizaje Profundo**

**Leidy Natalia León Carvajal**

**lnleonc@unal.edu.co**

# **Canalización de datos con Tensorflow**


### Importamos las librerías y utilidades necesarias para trabajar

In [3]:
import tensorflow as tf
import numpy as np

## **Construcción de Tensores**
### A continuación se presentan algunos ejemplos de tensores:

In [4]:
# Tensor de dimensión 0 
tensor0=tf.constant(8)
print(tensor0)

tf.Tensor(8, shape=(), dtype=int32)


In [5]:
# Tensor de dimesión 3
tensor3=tf.constant([2,4,6])
print(tensor3)

tf.Tensor([2 4 6], shape=(3,), dtype=int32)


In [6]:
# Tensor de dimensión 2-3
tensor23=tf.constant([[1,3,5],[2,4,6]])
print(tensor23)

tf.Tensor(
[[1 3 5]
 [2 4 6]], shape=(2, 3), dtype=int32)


In [7]:
# Tensor de dimensión 2-3-5: ([[[5elementos],[5elementos],[5elementos]],[[5elmentos],[5elementos],[5elementos]]]) 
tensor235=tf.constant([[[1,1,1,1,1],[2,2,2,2,2],[3,3,3,3,3]],[[4,4,4,4,4],[5,5,5,5,5],[6,6,6,6,6]]])
print(tensor235)

tf.Tensor(
[[[1 1 1 1 1]
  [2 2 2 2 2]
  [3 3 3 3 3]]

 [[4 4 4 4 4]
  [5 5 5 5 5]
  [6 6 6 6 6]]], shape=(2, 3, 5), dtype=int32)


In [8]:
print(tensor235.numpy())
print('\n',tensor235.numpy().shape)
print('\n',tensor235.shape)

[[[1 1 1 1 1]
  [2 2 2 2 2]
  [3 3 3 3 3]]

 [[4 4 4 4 4]
  [5 5 5 5 5]
  [6 6 6 6 6]]]

 (2, 3, 5)

 (2, 3, 5)


## **Álgebra de Tensores**
### Ahora veremos como efectuar algunas operaciones algebráicas entre tensores

In [9]:
# Construimos dos tensores a y b de la misma dimensión (2,3):
a=tf.constant([[1,3,5],[2,4,6]])
b=tf.constant([[1,2,3],[4,5,6]])

print(a)
print('\n',b)

tf.Tensor(
[[1 3 5]
 [2 4 6]], shape=(2, 3), dtype=int32)

 tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [10]:
# Suma de tensores (se realiza elemento a elemento):
suma=tf.add(a,b)
print(suma)

# O alternativamente
print('\n', a+b)

tf.Tensor(
[[ 2  5  8]
 [ 6  9 12]], shape=(2, 3), dtype=int32)

 tf.Tensor(
[[ 2  5  8]
 [ 6  9 12]], shape=(2, 3), dtype=int32)


In [11]:
# Producto de tensores componente a componente:
prodc=tf.multiply(a,b)
print(prodc)

# O también
print('\n', a*b)

tf.Tensor(
[[ 1  6 15]
 [ 8 20 36]], shape=(2, 3), dtype=int32)

 tf.Tensor(
[[ 1  6 15]
 [ 8 20 36]], shape=(2, 3), dtype=int32)


In [12]:
# Producto de tensores matricialmente: No se puede efectuar entre a y b pues no son conformables!!!

# Se generan dos tensores conformables para ilustrar la operación:
a1=tf.constant([[2,3],[4,8]])
b1=tf.constant([[1,2],[3,5]])
prodt=tf.matmul(a1,b1)
print(a1)
print('\n',b1)
print('\n',prodt)

# También podemos hacer
print('\n', a1@b1)

tf.Tensor(
[[2 3]
 [4 8]], shape=(2, 2), dtype=int32)

 tf.Tensor(
[[1 2]
 [3 5]], shape=(2, 2), dtype=int32)

 tf.Tensor(
[[11 19]
 [28 48]], shape=(2, 2), dtype=int32)

 tf.Tensor(
[[11 19]
 [28 48]], shape=(2, 2), dtype=int32)


## **Funciones de Reducción**
### Podemos extraer alguna información sobre los elementos de los tensores

In [13]:
# Construimos un tensor de dimensión 2-3 para ilustrar:
x=tf.constant([[1.0,13.0],[5.0,7.0]])
print(x)

# Identificamos el elemento mayor dentro del tensor:
print('\nELEMENTO MAYOR:',tf.reduce_max(x))
# Identificamos el elemento menor dentro del tensor:
print('\nELEMENTO MENOR:',tf.reduce_min(x))
# Calculamos el promedio de los componentes del tensor:
print('\nPROMEDIO DE LOS ELEMENTOS:',tf.reduce_mean(x))
# Identificamos la posición del elemento mayor dentro del tensor:
print('\nPOSICIÓN ELEMENTO MAYOR:',tf.argmax(x))
# Aplica la función de activación SOFTMAX a los componentes del tensor exp(e[i,j])/sum(exp(e[i,]))
print('\nSOFTMAX:\n',tf.nn.softmax(x))
# Se suman las probabilidades obtenidas con la función SOFTMAX para verificar que da 1:
print('\nSUMA PROBABILIDADES SOFTMAX:',tf.reduce_sum(tf.nn.softmax(x),axis=1),"\n")

tf.Tensor(
[[ 1. 13.]
 [ 5.  7.]], shape=(2, 2), dtype=float32)

ELEMENTO MAYOR: tf.Tensor(13.0, shape=(), dtype=float32)

ELEMENTO MENOR: tf.Tensor(1.0, shape=(), dtype=float32)

PROMEDIO DE LOS ELEMENTOS: tf.Tensor(6.5, shape=(), dtype=float32)

POSICIÓN ELEMENTO MAYOR: tf.Tensor([1 0], shape=(2,), dtype=int64)

SOFTMAX:
 tf.Tensor(
[[6.1441742e-06 9.9999380e-01]
 [1.1920291e-01 8.8079703e-01]], shape=(2, 2), dtype=float32)

SUMA PROBABILIDADES SOFTMAX: tf.Tensor([0.99999994 0.99999994], shape=(2,), dtype=float32) 



## **Tipo, Forma y Dimensión**
### Veremos cómo extraer algunas características de un tensor

In [14]:
# Construcción de un tensor 3-2-5 ([[[5e],[5e]],[[5e],[5e]],[[5e],[5e]]])

tensor=tf.constant([[[5,9,2,3,7],[8,8,7,0,4]],
                    [[3,9,8,0,3],[2,8,2,5,1]],
                    [[4,5,2,5,1],[4,7,0,6,7]]])
print('TIPO: ',tensor.dtype)
print('\nFORMA: ',tensor.shape)
print('\nDIMENSIÓN: ',tensor.ndim)
print('\nDIMENSIÓN DE UN COMPONENTE: ',tensor.shape[1])
print('\nNÚMERO DE ELEMENTOS: ',tf.size(tensor.numpy()))

TIPO:  <dtype: 'int32'>

FORMA:  (3, 2, 5)

DIMENSIÓN:  3

DIMENSIÓN DE UN COMPONENTE:  2

NÚMERO DE ELEMENTOS:  tf.Tensor(30, shape=(), dtype=int32)


## **Indexación**
### Se presenta la forma en que pueden manipularse los índices de un tensor

In [15]:
# Se construye un tensor para ilustrar el manejo de índices
tensor=tf.constant([10,4,14,15,3,4,10,19,19,6])
print(tensor)
print("\nPIMER ELEMENTO: ", tensor[0])
print("\nQUINTO ELEMENTO: ", tensor[4])
print("\nÚLTIMO EMENTO: ", tensor[-1].numpy())
print('\nTODOS LOS ELEMENTOS: ', tensor[:].numpy())
print('\nELEMENTOS ANTES DE LA POSICIÓN 5: ', tensor[:5].numpy())
print('\nELEMENTOS DESPUÉS DE LA POSICIÓN 5: ', tensor[5:].numpy())
print('\nDESDER LA POSICIÓN 4 HASTA LA POSICIÓN 6: ', tensor[4:7].numpy())
print('\nELEMENTOS EN LA POSICIÓN IMPAR: ', tensor[0::2].numpy())
print('\nELEMENTOS INVIRTIENDO EL ORDEN: ', tensor[::-1].numpy())

tf.Tensor([10  4 14 15  3  4 10 19 19  6], shape=(10,), dtype=int32)

PIMER ELEMENTO:  tf.Tensor(10, shape=(), dtype=int32)

QUINTO ELEMENTO:  tf.Tensor(3, shape=(), dtype=int32)

ÚLTIMO EMENTO:  6

TODOS LOS ELEMENTOS:  [10  4 14 15  3  4 10 19 19  6]

ELEMENTOS ANTES DE LA POSICIÓN 5:  [10  4 14 15  3]

ELEMENTOS DESPUÉS DE LA POSICIÓN 5:  [ 4 10 19 19  6]

DESDER LA POSICIÓN 4 HASTA LA POSICIÓN 6:  [ 3  4 10]

ELEMENTOS EN LA POSICIÓN IMPAR:  [10 14  3 10 19]

ELEMENTOS INVIRTIENDO EL ORDEN:  [ 6 19 19 10  4  3 15 14  4 10]


In [16]:
# Creamos un tensor 2-3 para ilustrar: ([[3e],[3e]])

t=tf.constant([[1,3,5],[2,4,6]])
print('TENSOR: ', t)

print('\nCOMPONENTE EN LA POSICIÓN 0-1 = ',t[0,1].numpy())
print('\nPRIMERA FILA: ', t[0,:].numpy())
print('\nPRIMERA COLUMNA: ', t[:,0].numpy())
print('\nÚLTIMA COLUMNA: ', t[:,-1].numpy())
print('\nPRIMER ELEMENTO DE LA ÚLTIMA COLUMNA: ', t[0,-1].numpy())
print('\nSALTAR LA PRIMERA COLUMNA:\n', t[:,1:].numpy())

TENSOR:  tf.Tensor(
[[1 3 5]
 [2 4 6]], shape=(2, 3), dtype=int32)

COMPONENTE EN LA POSICIÓN 0-1 =  3

PRIMERA FILA:  [1 3 5]

PRIMERA COLUMNA:  [1 2]

ÚLTIMA COLUMNA:  [5 6]

PRIMER ELEMENTO DE LA ÚLTIMA COLUMNA:  5

SALTAR LA PRIMERA COLUMNA:
 [[3 5]
 [4 6]]


In [17]:
# Creamos un vector 3-2-5 para ilustrar
tensor=tf.constant([[[0,2,4,6,8],[1,3,5,7,9]],[[10,12,14,16,18],[11,13,15,17,19]],[[20,22,24,26,28],[21,23,25,27,29]]])
print(tensor.shape,'\n')
print(tensor.numpy())

(3, 2, 5) 

[[[ 0  2  4  6  8]
  [ 1  3  5  7  9]]

 [[10 12 14 16 18]
  [11 13 15 17 19]]

 [[20 22 24 26 28]
  [21 23 25 27 29]]]


In [18]:
print('PRIMERA CAPA\n', tensor[0,:,:])
print('\nPRIMERA CAPA\n', tensor[0])
print('\nSEGUNDA CAPA\n', tensor[1])
print('\nTERCERA CAPA\n', tensor[2])

PRIMERA CAPA
 tf.Tensor(
[[0 2 4 6 8]
 [1 3 5 7 9]], shape=(2, 5), dtype=int32)

PRIMERA CAPA
 tf.Tensor(
[[0 2 4 6 8]
 [1 3 5 7 9]], shape=(2, 5), dtype=int32)

SEGUNDA CAPA
 tf.Tensor(
[[10 12 14 16 18]
 [11 13 15 17 19]], shape=(2, 5), dtype=int32)

TERCERA CAPA
 tf.Tensor(
[[20 22 24 26 28]
 [21 23 25 27 29]], shape=(2, 5), dtype=int32)


In [19]:
# Construimos un tensor para ilustrar cómo manipular la disposición de un tensor:
x = tf.constant([[2],[4],[6]])
print('FORMA: ', x.shape)
print('\nFORMA COMO LISTA: ',x.shape.as_list(),'\n')
reshaped = tf.reshape(x,[1,3])
print(reshaped.numpy(),'\n')
print(x.numpy())

FORMA:  (3, 1)

FORMA COMO LISTA:  [3, 1] 

[[2 4 6]] 

[[2]
 [4]
 [6]]


In [20]:
print("Tensor actual: \n", tensor.numpy())
flat = tf.reshape(tensor, [-1])
print("\n TENSOR APLANADO: \n", flat.numpy())

Tensor actual: 
 [[[ 0  2  4  6  8]
  [ 1  3  5  7  9]]

 [[10 12 14 16 18]
  [11 13 15 17 19]]

 [[20 22 24 26 28]
  [21 23 25 27 29]]]

 TENSOR APLANADO: 
 [ 0  2  4  6  8  1  3  5  7  9 10 12 14 16 18 11 13 15 17 19 20 22 24 26
 28 21 23 25 27 29]


In [21]:
print(tensor.shape.as_list(),'\n')
print(tf.reshape(tensor, [2*3,5]),'\n')
print(tf.reshape(tensor, [2,3*5]),'\n')
print(tf.reshape(tensor, [-1,5]),'\n')
print(tf.reshape(tensor, [3,-1]),'\n')
print(tf.reshape(tensor, [3,2,5]),'\n')

[3, 2, 5] 

tf.Tensor(
[[ 0  2  4  6  8]
 [ 1  3  5  7  9]
 [10 12 14 16 18]
 [11 13 15 17 19]
 [20 22 24 26 28]
 [21 23 25 27 29]], shape=(6, 5), dtype=int32) 

tf.Tensor(
[[ 0  2  4  6  8  1  3  5  7  9 10 12 14 16 18]
 [11 13 15 17 19 20 22 24 26 28 21 23 25 27 29]], shape=(2, 15), dtype=int32) 

tf.Tensor(
[[ 0  2  4  6  8]
 [ 1  3  5  7  9]
 [10 12 14 16 18]
 [11 13 15 17 19]
 [20 22 24 26 28]
 [21 23 25 27 29]], shape=(6, 5), dtype=int32) 

tf.Tensor(
[[ 0  2  4  6  8  1  3  5  7  9]
 [10 12 14 16 18 11 13 15 17 19]
 [20 22 24 26 28 21 23 25 27 29]], shape=(3, 10), dtype=int32) 

tf.Tensor(
[[[ 0  2  4  6  8]
  [ 1  3  5  7  9]]

 [[10 12 14 16 18]
  [11 13 15 17 19]]

 [[20 22 24 26 28]
  [21 23 25 27 29]]], shape=(3, 2, 5), dtype=int32) 



In [22]:
# Podemos convertir los tensores a distintos tipos empleando la función 'cast':
f64_tensor = tf.constant([9.0, 4.0, 7.0], dtype = tf.float64)
print(f64_tensor,'\n')

f16_tensor = tf.cast(f64_tensor,dtype= tf.float16)
print(f16_tensor,'\n')

u8_tensor = tf.cast(f16_tensor, dtype = tf.uint8)
print(u8_tensor,'\n')

tf.Tensor([9. 4. 7.], shape=(3,), dtype=float64) 

tf.Tensor([9. 4. 7.], shape=(3,), dtype=float16) 

tf.Tensor([9 4 7], shape=(3,), dtype=uint8) 



## **Radiodifusión**

In [23]:
a = tf.constant([2, 4 ,6])
b = tf.constant(5)
c = tf.constant([5, 5 ,5])

# Podemos producir el mismo resultado usando la siguiente sintaxis:
print(tf.multiply(a,5),'\n')
print(a*b,'\n')
print(a*c,'\n')

tf.Tensor([10 20 30], shape=(3,), dtype=int32) 

tf.Tensor([10 20 30], shape=(3,), dtype=int32) 

tf.Tensor([10 20 30], shape=(3,), dtype=int32) 



In [24]:
a = tf.reshape(a, [3,1])
b = tf.constant([2,4,6,8,10])
print(a, '\n')
print(b, '\n')
print(tf.multiply(a,b)) # Son conformables!!

tf.Tensor(
[[2]
 [4]
 [6]], shape=(3, 1), dtype=int32) 

tf.Tensor([ 2  4  6  8 10], shape=(5,), dtype=int32) 

tf.Tensor(
[[ 4  8 12 16 20]
 [ 8 16 24 32 40]
 [12 24 36 48 60]], shape=(3, 5), dtype=int32)


In [25]:
# Creamos un tensor 3-3 a partir de un componente
print(tf.broadcast_to([1,2,3], [3,3]))

tf.Tensor(
[[1 2 3]
 [1 2 3]
 [1 2 3]], shape=(3, 3), dtype=int32)


## **Tensores Irregulares**

Construimos un tensor irregular como el que se observa en la imagen:

<figure>
  <img src="raggedtensor.png" width="300px" alt="Tensor Irregular">
</figure>

In [26]:
ragged_list=[
    [0,1,2,3],
    [4],
    [5,6,7],
    [8,9]
]
ragged_t = tf.ragged.constant(ragged_list)

print(ragged_t.shape)

(4, None)


## **Tesores de String**

In [28]:
tt=tf.constant("Creamos un tensor con texto")
print(tt)

tf.Tensor(b'Creamos un tensor con texto', shape=(), dtype=string)


In [36]:
tt=tf.constant(["Creamos un tensor con texto",
               "Texto 2",
               "Texto 3",
               "Emoji",
               "😁"])
print(tt,'\n')
print('\n',tf.strings.split(tt))

tf.Tensor(
[b'Creamos un tensor con texto' b'Texto 2' b'Texto 3' b'Emoji'
 b'\xf0\x9f\x98\x81'], shape=(5,), dtype=string) 


 <tf.RaggedTensor [[b'Creamos', b'un', b'tensor', b'con', b'texto'], [b'Texto', b'2'], [b'Texto', b'3'], [b'Emoji'], [b'\xf0\x9f\x98\x81']]>


In [37]:
tt_split = tf.strings.split(tt)
for i in tt_split:
    print(i)

tf.Tensor([b'Creamos' b'un' b'tensor' b'con' b'texto'], shape=(5,), dtype=string)
tf.Tensor([b'Texto' b'2'], shape=(2,), dtype=string)
tf.Tensor([b'Texto' b'3'], shape=(2,), dtype=string)
tf.Tensor([b'Emoji'], shape=(1,), dtype=string)
tf.Tensor([b'\xf0\x9f\x98\x81'], shape=(1,), dtype=string)


In [39]:
# Podemos convertir un string en número:
tt = tf.constant("8 15 20.2")

print(tf.strings.to_number(tf.strings.split(tt, " ")))

tf.Tensor([ 8.  15.  20.2], shape=(3,), dtype=float32)


## **Tensores Dispersos**

In [40]:
# Construimos un tensor disperso
tensor_disp = tf.sparse.SparseTensor(indices = [[0,1], [1,2]],
                                       values = [1,2],
                                       dense_shape
                                        =[3,4])
print(tensor_disp, "\n")

# Ahora lo convertimos en un tensor denso
print(tf.sparse.to_dense(tensor_disp))

SparseTensor(indices=tf.Tensor(
[[0 1]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64)) 

tf.Tensor(
[[0 1 0 0]
 [0 0 2 0]
 [0 0 0 0]], shape=(3, 4), dtype=int32)
